<?php if (isset($flash) && $flash):?>
    <div class="row">
        <main class="col-sm-12 col-md-8 col-lg-9">
            <div class="row responsive-label">
                <div class="col-sm-12 col-md-3">

                </div>
                <div class="col-sm-12 col-md">
                    <p><mark class="secondary"><?=is_array($flash) ? $flash['message'] : $flash?></mark></p>
                </div>
            </div> 
        </main>
    </div>
<?php endif;?>
