<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Avto Salon VW - Admin Area</title>
    <script src="/assets/vendor/jquery.min.js" type="application/javascript"></script>
    <link rel="stylesheet" href="/assets/vendor/semantic.min.css">
    <script src="/assets/vendor/semantic.min.js" type="application/javascript"></script>
    <link rel="stylesheet" href="/admin/assets/style.css">
</head>
<body>
