<form class="ui form" action="/admin/actions/update_product.php" method="POST">
    <input type="hidden" name="parameter_id" value="<?=$parameter->id?>">
    <div class="field">
        <label for="name">Название</label>
        <input type="text" id="name" required name="name" value="<?=$flash?$flash['name']:''?>">
    </div>
    <div class="field">
        <input class="ui inverted green button" type="submit" value="Сохранить">
    </div>
</form>