<h1>Добавление значение характеристики</h1>
<?php include '_menu.phtml'?>
<div class="row">
    <main class="col-sm-12 col-md-8 col-lg-9">
        <form action="/admin/actions/add_parameter_value.php" method="POST">
        <input type="hidden" name="parameter_id" value="<?=$parameter->id?>">
            <fieldset>
                <legend>Новое значение для характеристики <?=$parameter->name?></legend>
                <div class="row responsive-label">
                    <div class="col-sm-12 col-md-3">
                        <label for="name">Название</label>
                    </div>
                    <div class="col-sm-12 col-md">
                        <input type="text" id="name" required name="name" value="<?=$flash?$flash['name']:''?>">
                    </div>
                </div>
                <div class="row responsive-label">
                    <div class="col-sm-12 col-md-3">
                      
                    </div>
                    <div class="col-sm-12 col-md">
                        <input class="tertiary" type="submit" value="Добавить">
                    </div>
                </div>
            </fieldset>
        </form>
    </main>
</div>