<form class="ui form" action="/admin/actions/auth.php" method="POST">
    <div class="field">
        <label for="login">Логин</label>
        <input type="text" id="login" required name="login">
    </div>
    <div class="field">
        <label for="pass">Пароль</label>
        <input type="password" id="pass" required name="pass">
    </div>
    <div class="field">
        <input class="ui blue button" type="submit" value="Отправить">
    </div>
</form>
