<form class="ui form" action="/admin/actions/update_product.php" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="id" value="<?=$product->id?>">
    <div class="field">
        <label for="name">Название</label>
        <input type="text" id="name" required name="name" value="<?=$product->name?>">
    </div>
    <div class="field">
        <label for="file">Фото</label>
        <input type="file" id="file" name="file">
    </div>
    <?php foreach ($parameters as $parameter):?>
        <div class="field">
            <label for="parameter_<?=$parameter->id?>"><?=$parameter->name?></label>
            <select name="parameter_<?=$parameter->id?>" id="parameter_<?=$parameter->id?>">
                <option value="">-- Выберите <?=mb_strtolower($parameter->name)?> --</option>
                <?php foreach ($parameter->values as $value):?>
                    <option value="<?=$value['id']?>" <?=in_array($value['id'], $parameterValuesId)?'selected="selected"':''?>><?=$value['name']?></option>
                <?php endforeach;?>
            </select>
        </div>
    <?php endforeach;?>
    <div class="field">
        <input class="ui inverted green button" type="submit" value="Сохранить">
    </div>
</form>