<form class="ui form" action="/admin/actions/update_parameter_value.php" method="POST">
    <input type="hidden" name="id" value="<?=$parameterValue->id?>">
    <div class="field">
        <label for="name">Название значения</label>
        <input type="text" id="name" required name="name" value="<?=$parameterValue->name?>">
    </div>
    <div class="field">
        <input class="ui inverted green button" type="submit" value="Сохранить">
    </div>
</form>