<h1>Управление товарами</h1>
<?php include '_menu.phtml';?>
<form>
    <input type="number" placeholder="Укажите НДС в %" required name="wat">
    <button class="ui inverted yellow button">Расчитать</button>
    <?php if ($wat):?>
        <p>Сумма товаров на складе включая НДС <?=$wat?>%: <mark><?=$summWithWat?></mark></p>
    <?php endif;?>
</form>
<form id="search">
    <input type="text" placeholder="Введите поисковую фразу" name="q" value="<?=$q?>">
    <select name="sort" class="ui fluid dropdown">
        <?php foreach ($sortLabels as $sortKey => $label):?>
            <option value="<?=$sortKey?>" <?=$sortKey == $currentSort ? 'selected="selected"':''?>$><?=$label?></option>
        <?php endforeach;?>
    </select>
    <button class="ui inverted orange button">Отправить</button>
    <?php if ($page > 1):?>
        <a href="?page=<?=$page-1?>&sort=<?=$currentSort?>&q=<?=$q?>" class="ui violet button">&laquo; Предыдущая страница</a>
    <?php endif?>
   
    <?php if ($page < ceil($productsCount/$perPage)):?>
        <a href="?page=<?=$page+1?>&sort=<?=$currentSort?>&q=<?=$q?>" class="ui violet button">Следущая страница &raquo;</a>
    <?php endif;?> 
</form>
<table class="ui celled table">
    <caption>Товары</caption>
    <thead>
        <tr>
            <th>id</th>
            <th>Название</th>
            <th>Цена</th>
            <?php foreach($parameters as $parameter):?>
                <th><?=$parameter->name?></th>
            <?php endforeach;?>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($products as $product):?>
        <tr>
            <td style="width: 20px;" data-label="id"><?=$product['id']?></td>
            <td data-label="Название"><?=$product['name']?></td>
            <td data-label="Цена"><?=$product['price']?></td>
            <?php foreach($parameters as $parameter):?>
            <td data-label="<?=$parameter->name?>"><?=@$parameterToProductToParameterValue[$parameter->id][$product['id']]['name']?></td>
            <?php endforeach;?>
            <td data-label="Действия">
                <a href="/admin/edit_product.php?id=<?=$product['id']?>" class="ui inverted green button">Редактировать</a>
                <a href="/admin/actions/remove_product.php?id=<?=$product['id']?>" onclick="return confirm('Удалить товар <?=$product['id']?>?')" class="ui inverted red button">Удалить</a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>